config/routes.rb
Rails.application.routes.draw do
  devise_for :restaurants, path: 'auth'

  root to: 'restaurants#show'

  resources :restaurants do
    resources :categories do
      resources :dishes do
        resources :toppings
      end
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :restaurant
  has_many :dishes, dependent: :destroy
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :category
  has_many :toppings, dependent: :destroy

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :categories, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
end

app/models/topping.rb
class Topping < ActiveRecord::Base
  belongs_to :dish
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_restaurant!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = current_restaurant.categories.new
  end

  def create
    @category = Category.new(category_params)
    @category.save
    render :show
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    render :show
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to restaurant_path
  end

  private

  def category_params
    params.require(:category).permit(:id, :restaurant_id, :name)
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @dish = @category.dishes.new
  end

  def create
    @category = Category.find(params[:category_id])
    @dish = Dish.new(dish_params)
    @dish.save
    render :show
  end

  def show
    @category = Category.find(params[:category_id])
    @dish = Dish.find(params[:id])
  end

  def edit
    @category = Category.find(params[:category_id])
    @dish = Dish.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @dish = Dish.find(params[:id])
    @dish.update(dish_params)
    render :show
  end

  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy
    redirect_to restaurant_path
  end

  private

  def dish_params
    params.require(:dish).permit(:id, :category_id, :name, :price, :image)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def show
  end

  def edit
  end

  def update
    current_restaurant.update(restaurant_params)
    render :show
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:id, :name)
  end
end

app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @dish = Dish.find(params[:dish_id])
    @topping = @dish.toppings.new
  end

  def create
    @category = Category.find(params[:category_id])
    @dish = Dish.find(params[:dish_id])
    @topping = Topping.new(topping_params)
    @topping.save
    render :show
  end

  def show
    @category = Category.find(params[:category_id])
    @dish = Dish.find(params[:dish_id])
    @topping = Dish.find(params[:id])
  end

  def edit
    @category = Category.find(params[:category_id])
    @dish = Dish.find(params[:dish_id])
    @topping = Dish.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @dish = Dish.find(params[:dish_id])
    @topping = Topping.find(params[:id])
    @topping.update(topping_params)
    render :show
  end

  def destroy
    @topping = Topping.find(params[:id])
    @topping.destroy
  end

  private

  def topping_params
    params.require(:topping).permit(:id, :dish_id, :name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.slim
= form_for [current_restaurant, @category] do |f|
  = f.text_field :name
  = f.hidden_field :restaurant_id
  = f.submit

app/views/categories/edit.slim
= render 'form'

app/views/categories/new.slim
= render 'form'

app/views/categories/show.slim
= link_to 'Back', restaurant_path(current_restaurant)
br
br
= link_to 'Edit', edit_restaurant_category_path(current_restaurant, @category)
'  |
= link_to 'Delete', restaurant_category_path(current_restaurant, @category), method: :delete
br
br
= link_to 'Add Dish', new_restaurant_category_dish_path(current_restaurant, @category)
h1 = @category.name
h2 Dishes:
ul
  - @category.dishes.each do |dish|
    li
      = link_to dish.name, restaurant_category_dish_path(current_restaurant, @category, dish)
      '
      = dish.price
      ' $

app/views/dishes/_form.slim
= form_for [current_restaurant, @category, @dish], html: { multipart: true } do |f|
  = f.text_field :name
  = f.text_field :price
  = f.file_field :image
  = f.hidden_field :category_id
  = f.submit

app/views/dishes/edit.slim
= render 'form'

app/views/dishes/new.slim
= render 'form'

app/views/dishes/show.slim
= link_to 'Back', restaurant_category_path(current_restaurant, @category)
br
br
= link_to 'Edit', edit_restaurant_category_dish_path(current_restaurant, @category, @dish)
'  |
= link_to 'Delete', restaurant_category_dish_path(current_restaurant, @category, @dish), method: :delete
br
br
= link_to 'Add Topping', new_restaurant_category_dish_topping_path(current_restaurant, @category, @dish)
h1
  = @dish.name
  '  |
  = @dish.price
  ' $
  = image_tag @dish.image.url(:medium)

ul
  - @dish.toppings.each do |topping|
    li
      = topping.name
      '
      = topping.price
      ' $

app/views/layouts/application.slim
doctype html
html
  head
    title Restorendo
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    p.notice = notice
    p.alert = alert

    = yield

app/views/restaurants/edit.slim
= form_for current_restaurant do |f|
  = f.text_field :name
  = f.submit

app/views/restaurants/show.slim
- if restaurant_signed_in?
  = link_to 'Sign out', destroy_restaurant_session_path, method: :delete
- else
  = link_to 'Sign in', new_restaurant_session_path

br
br
= link_to 'Edit Restaurant', edit_restaurant_path(current_restaurant)
h1 = current_restaurant.name
h2 Categories:
ul
  - current_restaurant.categories.each do |category|
    li = link_to category.name, restaurant_category_path(current_restaurant, category)
= link_to 'Add category', new_restaurant_category_path(current_restaurant)

app/views/toppings/_form.slim
= form_for [current_restaurant, @category, @dish, @topping] do |f|
  = f.text_field :name
  = f.text_field :price
  = f.hidden_field :dish_id
  = f.submit

app/views/toppings/edit.slim
= render 'form'

app/views/toppings/new.slim
= render 'form'

app/views/toppings/show.slim
= link_to 'Back', restaurant_category_dish_path(current_restaurant, @category, @dish)
br
br
= link_to 'Edit', edit_restaurant_category_dish_topping_path(current_restaurant, @category, @dish, @topping)
h1
  = @topping.name
  '  |
  = @topping.price
  ' $

/ ul
/   - @dish.dishes.each do |dish|
/     li = link_to dish.name, edit_restaurant_category_dish_path(current_restaurant, @dish, dish)